planetstest:
  extends:
      file: ../docker-compose.yml
      service: planets
  image: ${starwars_planets}
  links:
      - swapi:swapi.co

swapi:
  image: lordofthejars/wiremock:2.0.9-beta
  ports:
      - "80:80"
